version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/BTCPayServer.Plugins.IntegrationTests"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/BTCPayServer.Plugins.IntegrationTests"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-dependencies:
        patterns:
          - "*"